"""
Architect output schemas (Mermaid diagrams only).
"""
from pydantic import BaseModel, Field
from typing import List, Literal


class DiagramSchema(BaseModel):
    """Mermaid.js diagram definition generated by the Architect agent."""

    title: str = Field(..., description="Diagram title, e.g., 'System Architecture'")
    type: Literal["architecture", "erd"] = Field(..., description="Diagram category")
    mermaid: str = Field(..., description="Raw Mermaid.js syntax")


class ArchitectOutputSchema(BaseModel):
    """Architect agent output containing exactly two diagrams."""

    diagrams: List[DiagramSchema] = Field(..., description="Mermaid.js diagrams derived from the PRD")
